# Site settings
title: Your blog title goes here
description: >
  Your blog description
baseurl: "/blog"
url: "https://bastion-rs"
logo: "https://raw.githubusercontent.com/bastion-rs/bastion-rs.github.io/master/src/assets/images/bastion-logo.png"
twitter_username: bastion_rs
github_username: bastion-rs

# Build settings
highlighter: rouge

root: "https://bastion-rs"